#!/bin/sh

#find /usr/include /usr/local/include . -name "*.php" -o -name "*.lua" -o -name "*.h" -o -name "*.cpp" -o -name "*.c" -o -name "*.cc" -o -name "*.hpp" > cscope.files
find . -name "*.php" -o -name "*.lua" -o -name "*.h" -o -name "*.cpp" -o -name "*.c" -o -name "*.cc" -o -name "*.hpp" > cscope.files
cscope -bkq -i cscope.files
#ctags -R
ctags -R --c++-kinds=+p --fields=+iaS --extra=+q
#ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes --c-kinds=+p -R -f ~/.vim/systags /usr/include /usr/local/include
